[package]
name = "xz_fastcgi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastcgi = "*"
xz2 = "*"
ctrlc = "*"

[profile.release]
codegen-units = 1
lto = true
